name: EPG Merger

on:
  schedule:
    - cron: '0 */6 * * *' # Har 6 soatda avtomatik ishlaydi
  workflow_dispatch:      # Qo'lda ishga tushirish tugmasi

permissions:
  contents: write         # Botga fayllarni yozish ruxsatini beradi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG merge script
        run: python merge_epg.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "EPG avtomatik yangilandi"
          file_pattern: "merged_epg.xml"
